package controllers;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;
import java.util.HashSet;
import java.util.Set;

@ApplicationPath("api")
public class ApplicationConfig extends Application{

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new HashSet<>();
        // following code can be used to customize Jersey 2.0 JSON provider:
        try {
            resources.add(Class.forName("org.glassfish.jersey.jackson.JacksonFeature"));
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }
    //
//   /**
//    * Do not modify addRestResourceClasses() method. It is automatically re-generated by NetBeans REST support to
//    * populate given list with all resources defined in the project.
//    */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(controllers.TodoController.class);
    }
}
